[package]
name = "shoal-cli"
version.workspace = true
edition.workspace = true

[dependencies]
shoal-engine = { workspace = true }
shoal-s3 = { workspace = true }
shoal-types = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
